import os

#####################################
##### Projeto Escola - Versão 3 #####
#####################################

resp = ''
while resp != '0':
    os.system('clear')

    print("############################################")
    print("######       Projeto SIG-Escola       ######")
    print("############################################")
    print("#####      1 - Módulo Aluno            #####")
    print("#####      2 - Módulo Professor        #####")
    print("#####      3 - Módulo Turma            #####")
    print("#####      4 - Módulo Relatório        #####")
    print("#####      5 - Módulo Informações      #####")
    print("#####      0 - Sair                    #####")
    resp = input("##### Escolha sua opção: ")

    if resp == '1':
        print()
        print("############################################")
        print("#####           Módulo Aluno           #####")
        print("############################################")
        print("##### 1 - Cadastrar Aluno              #####")
        print("##### 2 - Exibir Dados do Aluno        #####")
        print("##### 3 - Alterar Dados do Aluno       #####")
        print("##### 4 - Excluir Aluno                #####")
        print("##### 0 - Retornar ao Menu Principal   #####")
        resp2 = input("##### Escolha sua opção: ")
        print()
        if resp2 == '1':
            os.system('clear')
            print()
            print("############################################")
            print("#####           Cadastra Aluno         #####")
            print("############################################")
            print()
            nome = input("##### Nome: ")
            print()
            matr = input("##### Matrícula: ")
            print()
            email = input("##### Email: ")
            print()
            fone = input("##### Celular: ")
            print()
            print("\tAluno cadastrado com sucesso!")
            print()
            print("\t=============================")
            print("\t=          ATENÇÃO          =")
            print("\t=   Isso é uma simulação!   =")
            print("\t= Esta funcionalidade ainda =")
            print("\t=  está sendo implementada. =")
            print("\t=============================")
            print()

        elif resp2 == '2':
            os.system('clear')
            print()
            print("############################################")
            print("#####        Exibe Dados do Aluno      #####")
            print("############################################")
            print()
            matr = input("##### Matrícula: ")
            print()
            print("##### Matrícula:", matr)
            print("##### Nome:      Fulano de Tal dos Anzóis")
            print("##### Email:     fulano.anzois@ufrn.edu.br")
            print("##### Celular:   (84) 88888-4444")
            print()
            print("\t=============================")
            print("\t=          ATENÇÃO          =")
            print("\t=      Dados simulados      =")
            print("\t= Esta funcionalidade ainda =")
            print("\t=  está sendo implementada. =")
            print("\t=============================")
            print()
            
        elif resp2 == '3':
            os.system('clear')
            print()
            print("############################################")
            print("#####       Altera Dados do Aluno      #####")
            print("############################################")
            print()
            matr = input("##### Matrícula: ")
            print()
            nome = input("##### Nome: ")
            print()
            email = input("##### Email: ")
            print()
            fone = input("##### Celular: ")
            print()
            print("Aluno alterado com sucesso!")
            print()
            print("\t=============================")
            print("\t=          ATENÇÃO          =")
            print("\t=      Dados simulados      =")
            print("\t= Esta funcionalidade ainda =")
            print("\t=  está sendo implementada. =")
            print("\t=============================")
            print()

        elif resp2 == '4':
            os.system('clear')
            print()
            print("############################################")
            print("#####         Exclui Aluno             #####")
            print("############################################")
            print()
            matr = input("##### Matrícula: ")
            print()
            print("Aluno excluído com sucesso!")
            print()
            print("\t=============================")
            print("\t=          ATENÇÃO          =")
            print("\t=      Dados simulados      =")
            print("\t= Esta funcionalidade ainda =")
            print("\t=  está sendo implementada. =")
            print("\t=============================")
            print()

        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '2':
        print()
        print("############################################")
        print("#####         Módulo Professor         #####")
        print("############################################")
        print("##### 1 - Cadastrar Professor          #####")
        print("##### 2 - Exibir Dados do Professor    #####")
        print("##### 3 - Alterar Dados do Professor   #####")
        print("##### 4 - Excluir Professor            #####")
        print("##### 0 - Retornar ao Menu Principal   #####")
        resp2 = input("##### Escolha sua opção: ")
        print()
        print("############################################")
        print("#####                                   ####")
        print("#####      Este módulo ainda está       ####")
        print("#####        em desenvolvimento         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '3':
        print()
        print("############################################")
        print("#####           Módulo Turma           #####")
        print("############################################")
        print("##### 1 - Cadastrar Turma              #####")
        print("##### 2 - Exibir Dados da Turma        #####")
        print("##### 3 - Alterar Dados da Turma       #####")
        print("##### 4 - Excluir Turma                #####")
        print("##### 0 - Retornar ao Menu Principal   #####")
        resp2 = input("##### Escolha sua opção: ")
        print()
        print("############################################")
        print("#####                                   ####")
        print("#####      Este módulo ainda está       ####")
        print("#####        em desenvolvimento         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '4':
        print()
        print("############################################")
        print("#####         Módulo Relatório         #####")
        print("############################################")
        print("##### 1 - Lista Geral de Alunos        #####")
        print("##### 2 - Lista Geral de Professores   #####")
        print("##### 3 - Lista Geral de Turmas        #####")
        print("##### 4 - Lista de Alunos por Turma    #####")
        print("##### 5 - Lista de Turmas p/ Professor #####")
        print("##### 0 - Retornar ao Menu Principal   #####")
        resp2 = input("##### Escolha sua opção: ")
        print()
        print("############################################")
        print("#####                                   ####")
        print("#####      Este módulo ainda está       ####")
        print("#####        em desenvolvimento         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '5':
        print()
        print("############################################")
        print("#####  Você está no Módulo Informações  ####")
        print("############################################")
        print()
        print("#####  Projeto de Gestão de uma Escola  ####")
        print("#####  Equipe de desenvolvimento:       ####")
        print("#####  * Flavius Gorgônio @flgorgonio   ####")
        print("#####  Licença Pública Geral GNU        ####")
        print("#####  www.gnu.org/licenses/gpl.html    ####")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '0':
        print()
        print("############################################")
        print("#####  Você encerrou o programa, até logo! #")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    else:
        print()
        print("############################################")
        print("#####   Você digitou uma opção inválida ####")
        print("############################################")
        print("#####                                   ####")
        print("#####      Retorne ao menu anterior     ####")
        print("#####         e tente novamente         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")

print("Você encerrou o programa!")
print("Até logo!")