from colorama import Fore,Back,Style,init
from time import sleep
opcao = ''
init(autoreset=True)

while opcao != 0: 
    
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║              SISTEMA DE GESTÃO DE HORÁRIOS ESCOLARES                       ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╠════════════════════════════════════════════════════════════════════════════╣")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                            MENU PRINCIPAL                                  ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╠════════════════════════════════════════════════════════════════════════════╣")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [1] Portal do Professor                                                  ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [2] Portal do Aluno                                                      ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [3] Relatório Sobre os Horários das Aulas                                ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [4] Informações do Sistema                                               ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [0] Sair do Sistema                                                      ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
    print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
    opcao = int(input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite a opção que deseja acessar: "))
    print()
    
    if opcao == 1:
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                           PORTAL DO PROFESSOR                              ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╠════════════════════════════════════════════════════════════════════════════╣")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [1] Cadastro do Professor                                                ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [2] Cadastro de Horários                                                 ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [3] Exclusão de Aulas                                                    ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [4] Verificação de Horários                                              ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
        opcao2 = int(input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite a opção que deseja acessar: "))
        
        if opcao2 == 1:
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                           CADASTRO DO PROFESSOR                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")

            nome = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite o nome do professor:  ")    
            print()
            email = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite o email do professor: ")
            print()
            disciplina = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite a disciplina que irá lecionar: ")

            print()
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                           CADASTRO CONCLUÍDO                               ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                 \u26A0 Atenção! Isso é apenas uma simulação!                    ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA CONTINUAR ")

        elif opcao2 == 2:
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                           CADASTRO DE HORÁRIOS                             ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            disciplina = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite o nome da disciplina: ")
            print()
            turma = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite a turma da aula: ")
            print()
            horario_comeco = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite o horário de começo da aula(1,6): ")
            print()
            horario_termino = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite o horário de término da aula(1,6): ")
            print()
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                           CADASTRO CONCLUÍDO                               ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                 \u26A0 Atenção! Isso é apenas uma simulação!                    ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA CONTINUAR ")

        elif opcao2 == 3:
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                           EXCLUSÃO DE HORÁRIOS                             ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            disciplina = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite o nome da disciplina: ")
            print()
            turma = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite a turma da aula: ")
            print()
            horario_comeco = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite o horário que a aula iria começar(1,6): ")
            print()
            horario_termino = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite o horário que a aula iria terminar(1,6): ")
            print()
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                        EXCLUSÃO DE HORÁRIOS CONCLUÍDA                      ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                 \u26A0 Atenção! Isso é apenas uma simulação!                    ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA CONTINUAR ")

        elif opcao2 == 4:
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                          VERIFICAÇÃO DE HORÁRIOS                           ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            
            disciplina = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite a disciplina: ")
            print()
            turma = input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite a turma que deseja verificar: ")
            print()
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                     VERIFICAÇÃO DE HORÁRIOS CONCLUÍDA                      ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                 \u26A0 Atenção! Isso é apenas uma simulação!                    ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            print()
            input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA CONTINUAR ")

        else:
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                             OPÇÃO INEXISTENTE                              ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                 \U0001F6A9 VOLTE AO MENU PRINCIPAL E REFAÇA A OPERAÇÃO             ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA PULAR ")
    
    elif opcao == 2:
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                           PORTAL DO ALUNO                                  ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╠════════════════════════════════════════════════════════════════════════════╣")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [1] Ver Grade Semanal de Aulas                                           ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   [2] Ver Horários Vagos                                                   ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
        opcao2 = int(input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tDigite a opção que deseja acessar: "))

        if opcao2 == 1:
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                       MÓDULO EM DESENVOLVIMENTO...                         ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA PULAR ")

        if opcao2 == 2:
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                       MÓDULO EM DESENVOLVIMENTO...                         ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA PULAR ")
        elif opcao2 > 2:
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                             OPÇÃO INEXISTENTE                              ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                 \u26A0 Atenção! Isso é apenas uma simulação!                    ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
            print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
            input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA PULAR ")
    elif opcao == 3:
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                       MÓDULO EM DESENVOLVIMENTO...                         ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
        input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA PULAR ")
    elif opcao == 4:
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                         INFORMAÇÕES DO SISTEMA                             ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╠════════════════════════════════════════════════════════════════════════════╣")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   SISTEMA DE GESTÃO PARA CONTROLE DE HORÁRIOS                              ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╠════════════════════════════════════════════════════════════════════════════╣")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   PROGRAMADOR: PÉRICLES RAFAEL A. LINHARES                                 ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╠════════════════════════════════════════════════════════════════════════════╣")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   EMAIL: pericles.linhares.170@ufrn.edu.br                                 ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╠════════════════════════════════════════════════════════════════════════════╣")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║   LICENÇA PÚBLICA GERAL - GNU | www.gnu.org/licenses/gpl.html              ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
        input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA PULAR ")
        
    elif opcao > 4:
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                             OPÇÃO INEXISTENTE                              ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╔════════════════════════════════════════════════════════════════════════════╗")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                 \U0001F6A9 VOLTE AO MENU PRINCIPAL E REFAÇA A OPERAÇÃO             ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"║                                                                            ║")
        print(Fore.LIGHTGREEN_EX + Back.WHITE + Style.BRIGHT+"╚════════════════════════════════════════════════════════════════════════════╝")
        input(Fore.LIGHTGREEN_EX + Style.BRIGHT+"\tAPERTE >ENTER< PARA PULAR ")

fim = ("""           ╔════════════════════════════════════════════════════════════════════════════╗
           ║                                                                            ║
           ║                       O PROGRAMA FOI ENCERRADO                             ║
           ║                                                                            ║
           ╚════════════════════════════════════════════════════════════════════════════╝""")

for letras in fim:
    print(letras, end = '')
    sleep(0.01)
print()